#!/bin/sh
# pkg - a wrapper around pkg_*

case "$1" in
    add*)
        shift
        printf 'install? [y/n]: '
        read
        [[ "$REPLY" == y ]] &&
            doas pkg_add "$@"
        ;;
    del*)
        shift
        doas pkg_delete "$@"
        ;;
    info*)
        shift
        doas pkg_info -Q "$@"
        ;;
    upd*)
        doas pkg_add -u
        ;;
esac
