#!/usr/bin/env bash

case "$1" in
    r*)
        doas pkill wpa_supplicant
        doas wpa_supplicant -i wlp2s0 -B -c /etc/wpa_supplicant.conf
        ;;
    n*)
        doas wpa_cli -i wlp2s0 select_network "$2"
        doas dhcpcd wlp2s0
        ;;
    l*)
        doas wpa_cli -i wlp2s0 list_networks
        ;;
    *)
        doas wpa_cli -i wlp2s0 "$*"
esac
